### PR TITLE
The 'nextweb' project milestone: Code review request

### PR DESCRIPTION
**Pull request by Cyrus-Kiprop**
The project was a great learning experience. My  partner and I loved it. It is at this juncture that we submit out project for a TSE code review.

- [ ] Please do review and give us your sincere thoughts on the project.  Thank you.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## status: Require Changes
## Hi Team,
Nice work done so far, here are a few things we need to address
- @SM
* [ ] The latest funding rounds of index.co has three columns. the other column does not display at small screen size, [check original page](https://thenextweb.com)
- @MD and @LG
* [ ] The page at these media screens has a big margin-left which is making the content of the page push to the right resulting in a horizontal scroll on the page, let us handle this flaw. [check original page](https://thenextweb.com)
#### your page ‎👇
Screenshot from 2020-01-16 18-59-21
Screenshot from 2020-01-16 18-59-27
check the left space...
#### Original page  ‎👇
Screenshot from 2020-01-16 18-59-34
Screenshot from 2020-01-16 18-59-50
Impressive first attempt,
KIndly make these changes and submit the project for review

**Comment by ivanid22** [comment]
Hello there Addo,

We fixed the horizontal scrolling issue, turned out to be an incorrect padding value on the main section.
The second issue however, we couldn't reproduce it. For us, the layout in the "latest rounds of funding of index.co" is showing correctly in all viewport width breakpoints: one column at under 768px, three columns between 768px and 1024px, and 4 columns at 1024px and over.

Would you kindly take another look at the section and provide us with further details?

Thank you very much for your feedback, we hope to hear from you soon.

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!
### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.

#### Implementation details


* CSS styles should use media queries for 3 breakpoints 

small: max-width around 700
medium: max-width around 1000
large: mwidth over 1000

screen


screen



### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Comment by ivanid22** [comment]
Hi Anna! Thanks for taking the time to review our code.

Concerning the breaking points, we used a different approach to achieve the three distinct versions for the site. We approached the site from a mobile-first perspective, setting the styles for small screens, and also the styles which would be shared on larger screen widths.

From there, we set the styles for the two larger breakpoints (768px and 1024px) using media queries with min-width, setting the specific styles for each section and overwriting the base styles as we needed.

What we achieved with this, is a layout with three distinct sets of styles: 
- One for small screens (screen width <= 767px).
- One for mediums screens (screen width between 768px and 1023px).
- One for large screens (screens with a minimum width of 1024px).

We're going to push a correction for the comments shortly,

Thanks again for your feedback, and we hope to hear from you soon!

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Cyrus-Kiprop    
#### Great Job so far, but there is one more thing required. 

### Page structure
- [x] Please let us fix the hamburger menu on the small screen.






### Make changes and submit another code review request.
*Happy coding*

**Comment by ivanid22** [comment]
Hi @kobiyoyo!

Thank you for providing us with your feedback!

We took a look at our code and the behavior of the site, but we couldn't reproduce this issue. We tested our code on Chrome and Firefox, both on Windows and Ubuntu/Debian. In all cases the hamburger menu icons are displayed correctly. Here's a link to a video testing the project on Windows:

https://www.loom.com/share/a8894aede21b4b5db35eeb8529777b1b

One thing to note, is that the icons themselves are being loaded from the Fontawesome CDN, maybe there's a bit of a delay until the icons are loaded and they show up on the menu. That could be the issue.

In any case, please let us know what you think.

Thanks again!

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Project looks amazing. Congratulation :+1: Approved.
Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Comment by ivanid22** [comment]
Thank you! @pelzolga123

**Pull request merged**
